from PyQt5 import QtCore, QtGui, QtWidgets
from test3 import Ui_mainWindow2


class Ui_MainWindow(object):
    def ui_main(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_mainWindow2()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1284, 600)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(248, 255, 172);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelwidget = QtWidgets.QListWidget(self.centralwidget)
        self.labelwidget.setGeometry(QtCore.QRect(1120, 30, 211, 660))
        self.labelwidget.setStyleSheet("border-color: rgb(97, 97, 97);")
        self.labelwidget.setObjectName("labelwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1120, 10, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, 80, 151, 640))
        self.listView.setAutoFillBackground(True)
        self.listView.setStyleSheet("border-color: rgb(93, 92, 85);")
        self.listView.setObjectName("listView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(10, 30, 70, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 50, 141, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.RunButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda :self.ui_main())
        self.RunButton.setGeometry(QtCore.QRect(20, 580, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RunButton.setFont(font)
        self.RunButton.setObjectName("RunButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar_2)
        self.action_New = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../work/scandatsource/scandat/resources/icons/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_New.setIcon(icon1)
        self.action_New.setObjectName("action_New")
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setIcon(icon1)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setIcon(icon1)
        self.action_save.setObjectName("action_save")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setIcon(icon1)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Copy_Previous_Bounding_Boxes_In_Current_Images = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../work/scandatsource/scandat/resources/icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Copy_Previous_Bounding_Boxes_In_Current_Images.setIcon(icon2)
        self.action_Copy_Previous_Bounding_Boxes_In_Current_Images.setObjectName("action_Copy_Previous_Bounding_Boxes_In_Current_Images")
        self.action_Open_Recent = QtWidgets.QAction(MainWindow)
        self.action_Open_Recent.setObjectName("action_Open_Recent")
        self.action_Save = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../work/scandatsource/scandat/resources/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save.setIcon(icon3)
        self.action_Save.setObjectName("action_Save")
        self.action_Save_As = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../work/scandatsource/scandat/resources/icons/save-as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save_As.setIcon(icon4)
        self.action_Save_As.setObjectName("action_Save_As")
        self.action_Close = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../work/scandatsource/scandat/resources/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Close.setIcon(icon5)
        self.action_Close.setObjectName("action_Close")
        self.action_Reset_All = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../../../work/scandatsource/scandat/resources/icons/resetall.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Reset_All.setIcon(icon6)
        self.action_Reset_All.setObjectName("action_Reset_All")
        self.action_Delet_Current_Image = QtWidgets.QAction(MainWindow)
        self.action_Delet_Current_Image.setIcon(icon5)
        self.action_Delet_Current_Image.setObjectName("action_Delet_Current_Image")
        self.action_Quit = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../../../work/scandatsource/scandat/resources/icons/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Quit.setIcon(icon7)
        self.action_Quit.setObjectName("action_Quit")
        self.action_Current_Rect_Box = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../../../pyqt5 icons/icons/icons/box-label.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Current_Rect_Box.setIcon(icon8)
        self.action_Current_Rect_Box.setObjectName("action_Current_Rect_Box")
        self.action_Edit_Label = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../../../pyqt5 icons/icons/icons/edit-signiture.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Edit_Label.setIcon(icon9)
        self.action_Edit_Label.setObjectName("action_Edit_Label")
        self.action_Duplicate_Rectbox = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../../../pyqt5 icons/icons/icons/box.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Duplicate_Rectbox.setIcon(icon10)
        self.action_Duplicate_Rectbox.setObjectName("action_Duplicate_Rectbox")
        self.action_Delete_Rectbox = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../resources/icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Delete_Rectbox.setIcon(icon11)
        self.action_Delete_Rectbox.setObjectName("action_Delete_Rectbox")
        self.action_Auto_SaveMode = QtWidgets.QAction(MainWindow)
        self.action_Auto_SaveMode.setObjectName("action_Auto_SaveMode")
        self.action_Single_class_Mode = QtWidgets.QAction(MainWindow)
        self.action_Single_class_Mode.setObjectName("action_Single_class_Mode")
        self.action_Display_Labels = QtWidgets.QAction(MainWindow)
        self.action_Display_Labels.setObjectName("action_Display_Labels")
        self.actionRun = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../../resources/icons/done.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon12, )
        self.actionRun.setObjectName("actionRun")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.action_tutorial = QtWidgets.QAction(MainWindow)
        self.action_tutorial.setObjectName("action_tutorial")
        self.action_Information = QtWidgets.QAction(MainWindow)
        self.action_Information.setObjectName("action_Information")
        self.action_Keyboard_Shortcuts = QtWidgets.QAction(MainWindow)
        self.action_Keyboard_Shortcuts.setObjectName("action_Keyboard_Shortcuts")
        self.actionzoom_in = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../../resources/icons/zoom-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionzoom_in.setIcon(icon13)
        self.actionzoom_in.setObjectName("actionzoom_in")
        self.actionzoom_out = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../../resources/icons/zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionzoom_out.setIcon(icon14)
        self.actionzoom_out.setObjectName("actionzoom_out")
        self.actionfit_window = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../../resources/icons/fit-window.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionfit_window.setIcon(icon15)
        self.actionfit_window.setObjectName("actionfit_window")
        self.toolBar_2.addAction(self.action_New)
        self.toolBar_2.addAction(self.action_open)
        self.toolBar_2.addAction(self.action_Copy_Previous_Bounding_Boxes_In_Current_Images)
        self.toolBar_2.addAction(self.action_Save)
        self.toolBar_2.addAction(self.action_Current_Rect_Box)
        self.toolBar_2.addAction(self.action_Edit_Label)
        self.toolBar_2.addAction(self.action_Duplicate_Rectbox)
        self.toolBar_2.addAction(self.action_Delete_Rectbox)
        self.toolBar_2.addAction(self.actionRun)
        self.toolBar_2.addAction(self.actionzoom_in)
        self.toolBar_2.addAction(self.actionzoom_out)
        self.toolBar_2.addAction(self.actionfit_window)
        self.toolBar_2.addAction(self.action_Reset_All)
        self.toolBar_2.addAction(self.action_Close)
        self.toolBar_2.addAction(self.action_Quit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scandat Studio"))
        self.label.setText(_translate("MainWindow", "Label List"))
        self.label_2.setText(_translate("MainWindow", "Box Labels"))
        self.checkBox.setText(_translate("MainWindow", "difficult"))
        self.checkBox_2.setText(_translate("MainWindow", "use_default_label"))
        self.RunButton.setText(_translate("MainWindow", "Run"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.action_New.setText(_translate("MainWindow", "&Open.."))
        self.action_New.setToolTip(_translate("MainWindow", "Open a new file"))
        self.action_New.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_open.setText(_translate("MainWindow", "&open_Dir"))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.action_save.setText(_translate("MainWindow", "&Change save Dir"))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.action_Exit.setText(_translate("MainWindow", "&Open Annotation"))
        self.action_Exit.setShortcut(_translate("MainWindow", "Ctrl+Shift+O"))
        self.action_Copy_Previous_Bounding_Boxes_In_Current_Images.setText(_translate("MainWindow", "&Copy Previous Bounding Boxes In Current Images"))
        self.action_Copy_Previous_Bounding_Boxes_In_Current_Images.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.action_Open_Recent.setText(_translate("MainWindow", "&Open Recent"))
        self.action_Save.setText(_translate("MainWindow", "&Save"))
        self.action_Save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_Save_As.setText(_translate("MainWindow", "&Save As"))
        self.action_Save_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.action_Close.setText(_translate("MainWindow", "&Close"))
        self.action_Close.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.action_Reset_All.setText(_translate("MainWindow", "&Reset All"))
        self.action_Delet_Current_Image.setText(_translate("MainWindow", "&Delet Current Image"))
        self.action_Delet_Current_Image.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.action_Quit.setText(_translate("MainWindow", "&Quit"))
        self.action_Quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_Current_Rect_Box.setText(_translate("MainWindow", "&Create Rect Box"))
        self.action_Current_Rect_Box.setShortcut(_translate("MainWindow", "W"))
        self.action_Edit_Label.setText(_translate("MainWindow", "&Edit Label"))
        self.action_Edit_Label.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.action_Duplicate_Rectbox.setText(_translate("MainWindow", "&Duplicate Rectbox"))
        self.action_Duplicate_Rectbox.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.action_Delete_Rectbox.setText(_translate("MainWindow", "&Delete Rectbox"))
        self.action_Delete_Rectbox.setShortcut(_translate("MainWindow", "Del"))
        self.action_Auto_SaveMode.setText(_translate("MainWindow", "&Auto SaveMode"))
        self.action_Single_class_Mode.setText(_translate("MainWindow", "&Single class Mode"))
        self.action_Display_Labels.setText(_translate("MainWindow", "&Display Labels"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionRun.setShortcut(_translate("MainWindow", "Alt+Shift+F10"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.action_tutorial.setText(_translate("MainWindow", "&tutorial "))
        self.action_Information.setText(_translate("MainWindow", "&Information"))
        self.action_Keyboard_Shortcuts.setText(_translate("MainWindow", "&Keyboard Shortcuts"))
        self.actionzoom_in.setText(_translate("MainWindow", "zoom_in"))
        self.actionzoom_in.setShortcut(_translate("MainWindow", "Ctrl+="))
        self.actionzoom_out.setText(_translate("MainWindow", "zoom_out"))
        self.actionzoom_out.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.actionfit_window.setText(_translate("MainWindow", "fit_window"))
        self.actionfit_window.setShortcut(_translate("MainWindow", "Ctrl+F"))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
